import pymongo

def updateCollection(client, dbString, data):
    collection = client['database'][dbString]
    collection.delete_many( { } )
    collection.insert_many(data)


# Not many documents for teams Braves -> D-backs
teams= {
    'Rays'          : 139,
    'Red Sox'       : 111,
    'Yankees'       : 147,
    'Blue Jays'     : 141,
    'Orioles'       : 110,
    'White Sox'     : 145,
    'Indians'       : 114,
    'Tigers'        : 116,
    'Royals'        : 118,
    'Twins'         : 142,
    'Astros'        : 117,
    'Athletics'     : 133,
    'Mariners'      : 136,
    'Angels'        : 108,
    'Rangers'       : 140,
    'Phillies'      : 143,
    'Braves'        : 144,
    'Mets'          : 121,
    'Nationals'     : 120,
    'Marlins'       : 146,
    'Brewers'       : 158,
    'Reds'          : 113,
    'Cardinals'     : 138,
    'Cubs'          : 112,
    'Pirates'       : 134,
    'Giants'        : 137,
    'Dodgers'       : 119,
    'Padres'        : 135,
    'Rockies'       : 115,
    'D-backs'       : 109
}

# Reduced Stats from Sensitivity Analysis

batting_stats = [
    'hr',
    # 'gidp',
    # 'sac',
    'rbi',
    'tb',
    # 'slg',
    'avg',
    # 'bb',
    'ops',
    # 'hbp',
    # 'g',
    # 'd',
    # 'e',
    'so',
    # 'sf',
    'tpa',
    # 'h',
    # 'cs',
    'obp',
    # 't',
    # 's',
    # 'r',
    # 'sb'
]

pitching_stats = [
    'hr',
    'wpct',
    'era',
    # 'bsv',
    'outs',
    # 'sho',
    # 'sv',
    'whip',
    # 'qs',
    # 'bb',
    # 'g',
    # 'hld',
    # 'so',
    # 'l',
    # 'hb',
    # 'svo',
    'h',
    'ip',
    # 'w',
    # 'r',
    'pa',
    # 'cg',
    # 'gs',
    # 'ibb',
    # 'er'
]

columns = [
    'home hr avg',
    # 'home gidp avg',
    # 'home sac avg',
    'home rbi avg',
    'home tb avg',
    # 'home slg avg',
    'home avg avg',
    # 'home bb avg',
    'home ops avg',
    # 'home hbp avg',
    # 'home g avg',
    # 'home d avg',
    # 'home e avg',
    'home so avg',
    # 'home sf avg',
    'home tpa avg',
    # 'home h avg',
    # 'home cs avg',
    'home obp avg',
    # 'home t avg',
    # 'home s avg',
    # 'home r avg',
    # 'home sb avg',
    'away hr avg',
    # 'away gidp avg',
    # 'away sac avg',
    'away rbi avg',
    'away tb avg',
    # 'away slg avg',
    'away avg avg',
    # 'away bb avg',
    'away ops avg',
    # 'away hbp avg',
    # 'away g avg',
    # 'away d avg',
    # 'away e avg',
    'away so avg',
    # 'away sf avg',
    'away tpa avg',
    # 'away h avg',
    # 'away cs avg',
    'away obp avg',
    # 'away t avg',
    # 'away s avg',
    # 'away r avg',
    # 'away sb avg',
    'home pitching hr',
    'home pitching wpct',
    'home pitching era',
    # 'home pitching bsv',
    'home pitching outs',
    # 'home pitching sho',
    # 'home pitching sv',
    'home pitching whip',
    # 'home pitching qs',
    # 'home pitching bb',
    # 'home pitching g',
    # 'home pitching hld',
    # 'home pitching so',
    # 'home pitching l',
    # 'home pitching hb',
    # 'home pitching svo',
    'home pitching h',
    'home pitching ip',
    # 'home pitching w',
    # 'home pitching r',
    'home pitching pa',
    # 'home pitching cg',
    # 'home pitching gs',
    # 'home pitching ibb',
    # 'home pitching er',
    'away pitching hr',
    'away pitching wpct',
    'away pitching era',
    # 'away pitching bsv',
    'away pitching outs',
    # 'away pitching sho',
    # 'away pitching sv',
    'away pitching whip',
    # 'away pitching qs',
    # 'away pitching bb',
    # 'away pitching g',
    # 'away pitching hld',
    # 'away pitching so',
    # 'away pitching l',
    # 'away pitching hb',
    # 'away pitching svo',
    'away pitching h',
    'away pitching ip',
    # 'away pitching w',
    # 'away pitching r',
    'away pitching pa',
    # 'away pitching cg',
    # 'away pitching gs',
    # 'away pitching ibb',
    # 'away pitching er',
    'umpire_id',
    'home win'
] 


# All Stats Includede

""" columns = [
    'home hr avg',
    'home gidp avg',
    'home sac avg',
    'home rbi avg',
    'home tb avg',
    'home slg avg',
    'home avg avg',
    'home bb avg',
    'home ops avg',
    'home hbp avg',
    'home g avg',
    'home d avg',
    'home e avg',
    'home so avg',
    'home sf avg',
    'home tpa avg',
    'home h avg',
    'home cs avg',
    'home obp avg',
    'home t avg',
    'home s avg',
    'home r avg',
    'home sb avg',
    'away hr avg',
    'away gidp avg',
    'away sac avg',
    'away rbi avg',
    'away tb avg',
    'away slg avg',
    'away avg avg',
    'away bb avg',
    'away ops avg',
    'away hbp avg',
    'away g avg',
    'away d avg',
    'away e avg',
    'away so avg',
    'away sf avg',
    'away tpa avg',
    'away h avg',
    'away cs avg',
    'away obp avg',
    'away t avg',
    'away s avg',
    'away r avg',
    'away sb avg',
    'home pitching hr',
    'home pitching wpct',
    'home pitching era',
    'home pitching bsv',
    'home pitching outs',
    'home pitching sho',
    'home pitching sv',
    'home pitching whip',
    'home pitching qs',
    'home pitching bb',
    'home pitching g',
    'home pitching hld',
    'home pitching so',
    'home pitching l',
    'home pitching hb',
    'home pitching svo',
    'home pitching h',
    'home pitching ip',
    'home pitching w',
    'home pitching r',
    'home pitching pa',
    'home pitching cg',
    'home pitching gs',
    'home pitching ibb',
    'home pitching er',
    'away pitching hr',
    'away pitching wpct',
    'away pitching era',
    'away pitching bsv',
    'away pitching outs',
    'away pitching sho',
    'away pitching sv',
    'away pitching whip',
    'away pitching qs',
    'away pitching bb',
    'away pitching g',
    'away pitching hld',
    'away pitching so',
    'away pitching l',
    'away pitching hb',
    'away pitching svo',
    'away pitching h',
    'away pitching ip',
    'away pitching w',
    'away pitching r',
    'away pitching pa',
    'away pitching cg',
    'away pitching gs',
    'away pitching ibb',
    'away pitching er',
    'umpire_id',
    'home win'
]

batting_stats = [
    'hr',
    'gidp',
    'sac',
    'rbi',
    'tb',
    'slg',
    'avg',
    'bb',
    'ops',
    'hbp',
    'g',
    'd',
    'e',
    'so',
    'sf',
    'tpa',
    'h',
    'cs',
    'obp',
    't',
    's',
    'r',
    'sb'
]

pitching_stats = [
    'hr',
    'wpct',
    'era',
    'bsv',
    'outs',
    'sho',
    'sv',
    'whip',
    'qs',
    'bb',
    'g',
    'hld',
    'so',
    'l',
    'hb',
    'svo',
    'h',
    'ip',
    'w',
    'r',
    'pa',
    'cg',
    'gs',
    'ibb',
    'er'
] """
